-- Add content_source field to track where content originated
-- 'wallabag': Content pulled from Wallabag (not regenerated)
-- 'wallacast': Content generated/regenerated by Wallacast
ALTER TABLE content_items
ADD COLUMN IF NOT EXISTS content_source VARCHAR(20) DEFAULT 'wallabag';

-- Mark existing items from Wallabag
UPDATE content_items
SET content_source = 'wallabag'
WHERE wallabag_id IS NOT NULL AND content_source IS NULL;

-- Mark items created locally in Wallacast
UPDATE content_items
SET content_source = 'wallacast'
WHERE wallabag_id IS NULL AND content_source IS NULL;
