-- Migration: Add summary columns to content_items
-- Enables Twitter-thread style article + comment summaries generated by the narration LLM.
-- Two separate summaries are stored: `summary` (article body) and `comment_summary` (discussion).

DO $$
BEGIN
  -- Article-body summary (paragraphs separated by blank lines, each <= 280 chars)
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'content_items' AND column_name = 'summary'
  ) THEN
    ALTER TABLE content_items ADD COLUMN summary TEXT DEFAULT NULL;
  END IF;

  -- Comments summary (the article is given to the LLM only as context). NULL when no comments
  -- or when the user disabled comment summaries.
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'content_items' AND column_name = 'comment_summary'
  ) THEN
    ALTER TABLE content_items ADD COLUMN comment_summary TEXT DEFAULT NULL;
  END IF;

  -- Separate from generation_status so auto-audio and auto-summary can run at the same time.
  -- Values: 'idle' | 'generating' | 'completed' | 'failed'
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'content_items' AND column_name = 'summary_status'
  ) THEN
    ALTER TABLE content_items ADD COLUMN summary_status VARCHAR(50) DEFAULT 'idle';
  END IF;

  -- Existence/recency indicator used by the library list to toggle Generate vs Regenerate.
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'content_items' AND column_name = 'summary_generated_at'
  ) THEN
    ALTER TABLE content_items ADD COLUMN summary_generated_at TIMESTAMP DEFAULT NULL;
  END IF;
END $$;
